config/routes.rb
Searchapp::Application.routes.draw do
  get '/search', to: 'search#index', as: 'search'

  resources :authorships

  resources :authors

  resources :categories

  root to: 'search#index'

  resources :articles do
    collection { get :search }
  end

end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :article, touch: true

  belongs_to :author
  # attr_accessible :title, :body
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController
  # GET /authorships
  # GET /authorships.json
  def index
    @authorships = Authorship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authorships }
    end
  end

  # GET /authorships/1
  # GET /authorships/1.json
  def show
    @authorship = Authorship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authorship }
    end
  end

  # GET /authorships/new
  # GET /authorships/new.json
  def new
    @authorship = Authorship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authorship }
    end
  end

  # GET /authorships/1/edit
  def edit
    @authorship = Authorship.find(params[:id])
  end

  # POST /authorships
  # POST /authorships.json
  def create
    @authorship = Authorship.new(params[:authorship])

    respond_to do |format|
      if @authorship.save
        format.html { redirect_to @authorship, notice: 'Authorship was successfully created.' }
        format.json { render json: @authorship, status: :created, location: @authorship }
      else
        format.html { render action: "new" }
        format.json { render json: @authorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorships/1
  # PUT /authorships/1.json
  def update
    @authorship = Authorship.find(params[:id])

    respond_to do |format|
      if @authorship.update_attributes(params[:authorship])
        format.html { redirect_to @authorship, notice: 'Authorship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorships/1
  # DELETE /authorships/1.json
  def destroy
    @authorship = Authorship.find(params[:id])
    @authorship.destroy

    respond_to do |format|
      format.html { redirect_to authorships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/views/authorships/_form.html.erb
<%= form_for(@authorship) do |f| %>
  <% if @authorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorship.errors.count, "error") %> prohibited this authorship from being saved:</h2>

      <ul>
      <% @authorship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article %><br />
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorships/edit.html.erb
<h1>Editing authorship</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorship %> |
<%= link_to 'Back', authorships_path %>

app/views/authorships/index.html.erb
<h1>Listing authorships</h1>

<table>
  <tr>
    <th>Article</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorships.each do |authorship| %>
  <tr>
    <td><%= authorship.article %></td>
    <td><%= authorship.author %></td>
    <td><%= link_to 'Show', authorship %></td>
    <td><%= link_to 'Edit', edit_authorship_path(authorship) %></td>
    <td><%= link_to 'Destroy', authorship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorship', new_authorship_path %>

app/views/authorships/new.html.erb
<h1>New authorship</h1>

<%= render 'form' %>

<%= link_to 'Back', authorships_path %>

app/views/authorships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @authorship.article %>
</p>

<p>
  <b>Author:</b>
  <%= @authorship.author %>
</p>


<%= link_to 'Edit', edit_authorship_path(@authorship) %> |
<%= link_to 'Back', authorships_path %>